### PR TITLE
fix: use ecto migrator with_repo to avoid swallowing errors

### LINKED ISSUE #56: Ensure that migration failures propagate

### PR DESCRIPTION
**Pull request by jarlah**
fixes #56

### CODE REVIEW

File: lib/ecto.ex [hunk 1]
```diff
@@ -291,17 +289,27 @@ defmodule Testcontainers.Ecto do
...
         {:error, reason}
     end
   end
 
+  defp run_migrations(repo, migrations_path) do
+    try do
+      Ecto.Migrator.with_repo(
+        repo,
+        &Ecto.Migrator.run(&1, migrations_path, :up, all: true)
+      )
```
Comment (stabenfeldt) [inline lib/ecto.ex:306]: Please fix these warnings.

**Review by stabenfeldt — CHANGES_REQUESTED** [review]

File: lib/ecto.ex (hunk 1 above)
Comment (jarlah) [reply lib/ecto.ex:306]: the reason why these errors show up is because I test that its possible to build an example project that doesn't have ecto in dependencies. It should be possible to use testcontainers without ecto. On the other side I have made an issue here https://github.com/testcontainers/testcontainers-elixir/issues/53 previously about the need for (possibly?) to move the ecto logic into its own package, which then depends on testcontainers for elixir
