### PR TITLE
fix: log warning when using network_mode=host on macos/windows

### LINKED ISSUE #111: Consider strategies if network_mode is not supported
Following changes from https://github.com/testcontainers/testcontainers-elixir/pull/107

Either fail container creation if network_mode is not supported, aka the host machine is macOS, or diff the the values got back from docker engine after creation and log some error message if the desired container state does not meet the actual container state

### PR DESCRIPTION
**Pull request by jarlah**
fixes #111

just a suggestion for now. Might not amount to a merge. But i dont like this feature bleeding into windows or macos hosts when its not usable or tested without using direct host ip address.

### CODE REVIEW

File: lib/container.ex [hunk 1]
```diff
@@ -177,6 +187,11 @@ defmodule Testcontainers.Container do
   @doc """
   Sets a network mode to apply to the container object in docker.
   """
+  def with_network_mode(%__MODULE__{} = config, "host") when not is_os(:linux) do
```
Comment (jarlah) [inline lib/container.ex:190]: Should propably use guard and case insensitive match, instead of direct match

File: lib/container.ex [hunk 2]
```diff
@@ -177,6 +187,11 @@ defmodule Testcontainers.Container do
   @doc """
   Sets a network mode to apply to the container object in docker.
   """
+  def with_network_mode(%__MODULE__{} = config, mode = "host") when not is_os(:linux) do
```
Comment (jarlah) [inline lib/container.ex:190]: Should propably use guard and case insensitive match, instead of direct match
